Remove Rabbit URL from logging message
ONSdigital/sdx-receipt-ctp pull request #27
Opened 2017-03-22 10:39 UTC by gavinleeedwards

Remove Rabbit URL from logging message to prevent Rabbit credentials being logged out.

2017-03-22 11:29 UTC, JamesGardiner approved these changes

2017-03-22 15:28 UTC, necrophonic requested changes

2017-03-22 15:28 UTC, necrophonic commented on app/async_consumer.py
> +                logger.info('Connecting', attempt=count)
Connecting to what though? Should at least say "Connecting to queue server" or similar without revealing actual rabbit details.

2017-03-22 15:28 UTC, necrophonic commented on app/async_consumer.py
> +                logger.error("Connection error", exception=e)
Same as above - should add a bit of context about which connection the error refers to.

2017-03-22 16:11 UTC, necrophonic approved these changes

2017-03-23 10:12 UTC, necrophonic commented
Changes have already been merged in a hotfix

2017-03-23 10:12 UTC, closed without merging